# Generated by Django 4.1.6 on 2023-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=30)),
                ('song_id', models.CharField(max_length=25)),
                ('songDuration', models.TimeField()),
            ],
        ),
    ]
