# Generated by Django 4.1.6 on 2023-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistTitle', models.CharField(max_length=40)),
                ('playlist_id', models.CharField(max_length=25)),
            ],
        ),
    ]
