# Generated by Django 4.1.6 on 2023-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_id',
        ),
    ]
